### POST gemini test
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyAro1HcDM1LCJ5b8lNmHCheQtw7mmpXOEw
Content-Type: application/json

{
  "contents": [{
    "parts":[{"text": "오늘 저녁 메뉴 추천해줘"}]
  }]
}
###